stack_name: walkthrough-preprod
environment: preproduction
paas_environment: production

layers:
  - dns:
      - name: 'walkthrough.preprod.paas.aws.vodafone.com.au'
    instances:
      ami_name: <%=ami_name%>
      env:
        LOG_FILENAME: walkthrough-preprod
